In [3]:
list_two = list(range(1,4))
list_three = list(range(1,4))
list_sum = []

for index in range(3):
    list_two[index] = list_two[index] **2
    list_three[index] = list_three[index] **3
    list_sum.append(list_two[index] + list_three[index])
print(list_sum)

[2, 12, 36]


In [11]:
import numpy as np

array_two = np.arange(1,4)
print(array_two)

[1 2 3]


In [12]:
sample_array = np.array([1, 2, 3])

In [5]:
array_three = np.arange(1,4) **3
print(array_three)

[ 1  8 27]


In [6]:
print(array_two + array_three)

[ 2 10 30]


In [9]:
print(np.power(np.array([1, 2, 3]), 4))

[ 1 16 81]


In [10]:
np.negative(np.array([1, 2, 3]))

array([-1, -2, -3])

In [13]:
np.log(sample_array)

array([ 0.        ,  0.69314718,  1.09861229])

In [14]:
np.sin(sample_array)

array([ 0.84147098,  0.90929743,  0.14112001])

# Multidimensional Arrays

In [29]:
x = np.arange(3)
y = np.arange(3, 6)
z = np.arange(6, 9)

multi_array = np.array([x, y, z], dtype = np.int16)
print(multi_array)
print(multi_array.shape)
multi_array[1, 0] # row, column

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


3

In [30]:
print(multi_array.dtype)

int16


In [20]:
w = np.linspace(1, 10, 50) # 3. amount of samples
print(w)

[  1.           1.18367347   1.36734694   1.55102041   1.73469388
   1.91836735   2.10204082   2.28571429   2.46938776   2.65306122
   2.83673469   3.02040816   3.20408163   3.3877551    3.57142857
   3.75510204   3.93877551   4.12244898   4.30612245   4.48979592
   4.67346939   4.85714286   5.04081633   5.2244898    5.40816327
   5.59183673   5.7755102    5.95918367   6.14285714   6.32653061
   6.51020408   6.69387755   6.87755102   7.06122449   7.24489796
   7.42857143   7.6122449    7.79591837   7.97959184   8.16326531
   8.34693878   8.53061224   8.71428571   8.89795918   9.08163265
   9.26530612   9.44897959   9.63265306   9.81632653  10.        ]


In [22]:
b = np.arange(1, 30, 3) # 3. step size
print(b)

[ 1  4  7 10 13 16 19 22 25 28]


# 1D Slicing

In [31]:
x = np.arange(1, 10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [34]:
print(x[2:7:2])
print(x[:7])

[3 5 7]
[1 2 3 4 5 6 7]


# Reshaping

In [36]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [38]:
y = np.arange(18).reshape(3,3,2)
print(y)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


# Multi D Slicing

In [39]:
v = np.arange(18).reshape(3, 2, 3)
print(v)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [45]:
v[2, 0, 1] # "row" row column

13

In [49]:
v[1, :2, :3] # up to

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
v[1, ...]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [51]:
v[:, 0 ,0]

array([ 0,  6, 12])

In [52]:
v[1, :2, :3 :2] #step size

array([[ 6,  8],
       [ 9, 11]])

In [54]:
comparison_operation = v > 5
print(comparison_operation)

[[[False False False]
  [False False False]]

 [[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]]


In [59]:
v.max()

17

In [58]:
v[v>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

# Manipulating Array shapes

In [65]:
x = v = np.arange(18).reshape(3, 2, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [63]:
ravelled_array = x.ravel()
ravelled_array[2] = 1000000
print(ravelled_array) # shows a view/link and modify the original array
print(x)

[      0       1 1000000       3       4       5       6       7       8
       9      10      11      12      13      14      15      16      17]
[[[      0       1 1000000]
  [      3       4       5]]

 [[      6       7       8]
  [      9      10      11]]

 [[     12      13      14]
  [     15      16      17]]]


In [66]:
flattened_array = x.flatten() # creates a copy
flattened_array[2] = 100000
print(flattened_array)
print(x)

[     0      1 100000      3      4      5      6      7      8      9
     10     11     12     13     14     15     16     17]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [69]:
y = np.arange(9)
y.shape = [3,3]
print(y)
print(y.transpose())
print(y.T) # the same

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [71]:
print(np.resize(y, (6,6))) # array is repeated to fill the new array out

[[0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]
 [0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]]


In [76]:
print(np.zeros((2, 3), dtype=int)) # np.ones

[[0 0 0]
 [0 0 0]]


In [79]:
print(np.eye(3))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [80]:
np.random.rand(4, 4)

array([[ 0.44248756,  0.14623402,  0.15948579,  0.75330484],
       [ 0.18549767,  0.58641699,  0.5675857 ,  0.82629648],
       [ 0.41716248,  0.1418327 ,  0.39397801,  0.47905398],
       [ 0.61532089,  0.58155365,  0.93785992,  0.90053486]])

# Matrix Multiplication

In [82]:
mat_a = np.matrix([0, 3, 5, 5, 5, 2]).reshape(2, 3)
mat_a

matrix([[0, 3, 5],
        [5, 5, 2]])

In [83]:
mat_b = np.matrix([3, 4, 3, -2, 4, -2]).reshape(3, 2)
mat_b

matrix([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [84]:
mat_a * mat_b

matrix([[ 29, -16],
        [ 38,   6]])

In [86]:
product = np.matmul(mat_a, mat_b)
product
# same for arrays

matrix([[ 29, -16],
        [ 38,   6]])

# Stacking

In [91]:
x = np.arange(4).reshape(2, 2)
print(x)
print(x.shape)

[[0 1]
 [2 3]]
(2, 2)


In [88]:
y = np.arange(4, 8).reshape(2, 2)
print(y)

[[4 5]
 [6 7]]


In [93]:
z = np.hstack((x, y)) # shape of first axis must be the same
print(z)
print(z.shape) # more columns

[[0 1 4 5]
 [2 3 6 7]]
(2, 4)


In [95]:
g = np.vstack((x, y)) # shape of all but the second dimensions must be the same
print(g)
print(g.shape) # more rows

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)


In [97]:
w = np.concatenate((x, y), axis = 0) # vertical stacking, axis=1 horizontal stacking
print(w)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [99]:
print(w == g)

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


In [101]:
# Depth Stacking
depth_stack = np.dstack((x, y)) # adds an extra dimension
depth_stack

array([[[0, 4],
        [1, 5]],

       [[2, 6],
        [3, 7]]])

In [102]:
print(depth_stack.shape)

(2, 2, 2)


In [104]:
print(np.column_stack((x,y))) 
print(np.column_stack((x,y)) == np.hstack((x,y))) # same as horizontal array

[[0 1 4 5]
 [2 3 6 7]]
[[ True  True  True  True]
 [ True  True  True  True]]


In [105]:
# DIFFERS when 1D Shape
x = np.arange(4)
y = np.arange(4)

In [109]:
print(np.column_stack((x,y)))
print(np.column_stack((x,y))) 
print(np.hstack((x,y)))

[[0 0]
 [1 1]
 [2 2]
 [3 3]]
[[0 0]
 [1 1]
 [2 2]
 [3 3]]
[0 1 2 3 0 1 2 3]


In [113]:
x = np.arange(4).reshape(2,2)
y = np.arange(4).reshape(2,2)
x
y

array([[0, 1],
       [2, 3]])

In [112]:
print(np.row_stack((x,y)))

[[0 1]
 [2 3]
 [0 1]
 [2 3]]
